# Generated by Django 6.0.4 on 2026-05-21 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_name', models.CharField(max_length=200)),
                ('domain', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('text', models.TextField()),
                ('pubDate', models.DateTimeField()),
                ('link', models.URLField()),
                ('cat', models.ManyToManyField(to='scrapper.keywords')),
                ('media', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='scrapper.media')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
