# Generated by Django 6.0.4 on 2026-05-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywords',
            options={'verbose_name_plural': 'Keywords'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'Media'},
        ),
        migrations.AlterField(
            model_name='media',
            name='domain',
            field=models.URLField(unique=True),
        ),
    ]
