# Generated by Django 5.2.9 on 2026-06-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_alter_keywords_options_alter_media_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cat',
            field=models.ManyToManyField(related_name='category', to='scrapper.keywords'),
        ),
    ]
